week4/solutions/day1/word_central/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Same as get "/", to: "site#home"
  root "site#home"

  get "/text_inspections/new", to: "text_inspections#new"
  post "/text_inspections", to: "text_inspections#create"

  get "/asciis/new", to: "asciis#new"
  post "/asciis", to: "asciis#create"
end

week4/solutions/day1/word_central/app/controllers/asciis_controller.rb
class AsciisController < ApplicationController
  def new
    render :new
  end

  def create
    asciifier = Artii::Base.new :font => "doh"
    @text = params[:ascii][:text]
    @ascii_text = asciifier.asciify(@text)

    render :ascii_results
  end
end

week4/solutions/day1/word_central/app/controllers/text_inspections_controller.rb
class TextInspectionsController < ApplicationController
  def new
    render :new
  end

  def create
    @text = params[:text_inspection][:user_text]
    words_array = @text.split(" ")
    @word_count = words_array.length
    @estimated_seconds = @word_count * (60.0 / 275.0)

    word_count = Hash.new(0)
    words_array.each do |one_word|
      word_count[one_word] += 1
    end

    all_words_sorted = word_count.sort_by { |word, count| -count }
    @top_ten_words = all_words_sorted.first(10)

    render :results
  end
end

week4/solutions/day1/word_central/app/helpers/asciis_helper.rb
module AsciisHelper
end

week4/solutions/day1/word_central/app/helpers/text_inspections_helper.rb
module TextInspectionsHelper
end

week4/solutions/day1/word_central/app/views/text_inspections/new.html.erb
<h2> Inspect Your Text </h2>

<form method="post" action="/text_inspections">
  <div>
    <label for="text_inspection_user_text">
      Text
    </label>
    <textarea name="text_inspection[user_text]" id="text_inspection_user_text"></textarea>
  </div>

  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <button> Inspect </button>
</form>

week4/solutions/day1/word_central/app/views/text_inspections/results.html.erb
<h2> Inspection Results </h2>

<p> Submitted text: </p>

<blockquote> <%= @text %> </blockquote>

<p>
  Your text has roughly
  <strong> <%= @word_count %> </strong>
  words in it.
</p>

<p>
  It would take the average person
  <strong> <%= @estimated_seconds.round(1) %> seconds </strong>
  to read through it.
</p>


<h3> Top 10 most used words </h3>

<ol>
  <% @top_ten_words.each do |mini_word_array| %>
    <li>
      <!-- Word -->
      <strong> <%= mini_word_array[0] %> </strong>

      <!-- Count -->
      - <%= mini_word_array[1] %>
    </li>
  <% end %>
</ol>

<%= link_to "Inspect some more text", text_inspections_new_path %>