week4/timetracking/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get("/", { :to => "site#home" })
  # get("/", { to: "site#home" })
  # get "/", { to: "site#home" }

  get "/", to: "site#home"
    # app/views/site/home.html.erb

  get "/contact", to: "site#contact"
    # app/views/site/contact.html.erb

  get "/say_name/:name", to: "site#say_name"


  get "/calculator", to: "calculator#add_form"
  post "/calculate", to: "calculator#process_addition"
    # <form method="post" action="/calculate">


  resources :projects do
    resources :time_entries
  end

end

week4/timetracking/app/models/project.rb
class Project < ApplicationRecord
  has_many :time_entries
    # project_id of the TimeEntry model

  validates :name, { presence: true, uniqueness: true }
  validates :name, { length: { maximum: 30 } }
  validates :name, { format: /\A[a-zA-Z0-9 .']+\z/ }
end

week4/timetracking/app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :project
    # project_id
    # id of the Project model

  validates :hours, { numericality: true }
  validates :minutes, { numericality: true }
  validates :date, { presence: true }
end

week4/timetracking/app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  def add_form
    render "add_form"
  end


  def process_addition
    @a = params[:first_num].to_i
    @b = params[:second_num].to_i
    @result = @a + @b

    render "results"
  end
end

week4/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
                       .order(created_at: "desc")
                       .limit(10)
    render :index
  end

  def show
    @my_project = Project.find(params[:id])
    render :show
  end

  def new
    @my_project = Project.new
    render :new
  end

  def create
    @my_project = Project.new(
      :name => params[:project][:name],
      :description => params[:project][:description])
    @my_project.save

    redirect_to project_path(@my_project)
  end
end

week4/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    render "home"
  end

  def contact
    render "contact"
  end

  def say_name
    @name = params[:name]

    render "say_name"
  end
end

week4/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  def index
    @my_project = Project.find(params[:project_id])
    @my_entries = @my_project.time_entries

    render :index
  end

  def new
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.new

    render :new
  end

  def create
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.new(entry_params)

    if @my_entry.save
      redirect_to  project_time_entries_path(@my_project)
    else
      render :new
    end
  end


  def edit
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.find(params[:id])

    render :edit
  end

  def update
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.find(params[:id])

    if @my_entry.update(entry_params)
      redirect_to  project_time_entries_path(@my_project)
    else
      render :edit
    end
  end

  def destroy
    # 1) retrieve the project from the db
    my_project = Project.find(params[:project_id])

    # 2) retrieve the time entry from the db
    my_entry = my_project.time_entries.find(params[:id])

    # 3) delete the time entry from the db
    my_entry.destroy

    # 4) redirect away
    redirect_to  project_time_entries_path(my_project)
  end


  private

  def entry_params
    params.require(:time_entry).permit(:hours, :minutes, :date, :comments)
      #                 |                |
      #             -----     ------------
      #             |         |
      # params[:time_entry][:hours]
  end
end

week4/timetracking/app/helpers/calculator_helper.rb
module CalculatorHelper
end

week4/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

week4/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

week4/timetracking/app/views/blah/_navigation.html.erb
<!-- app/views/blah/_navigation.html.erb -->
<!--                |                    -->
<!--      Rails needs the underscore     -->

<ul>
  <li> <a href="/"> Home </a> </li>
  <li> <a href="/contact"> Contact </a> </li>
  <li> <a href="/calculator"> Addition </a> </li>
  <li> <%= link_to "List of Projects", projects_path %> </li>
</ul>

week4/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>
        <a href="/">
          Tmtrckng
        </a>
      </h1>

      <%= render "blah/navigation" %>
      <!--                   |                 -->
      <!-- app/views/blah/_navigation.html.erb -->
    </header>

    <%= yield %>

    <footer>
      <p> Made with &hearts; at Ironhack. </p>
    </footer>
  </body>
</html>

week4/timetracking/app/views/time_entries/_form.html.erb
<% if @my_entry.errors.any? %>
  <ul>
      <% @my_entry.errors.full_messages.each do |error_message| %>
        <li> <%= error_message %> </li>
      <% end %>
  </ul>
<% end %>


<%= form_for [@my_project, @my_entry] do |f| %>
  <div>
    <%= f.label :hours %>
    <%= f.number_field :hours %>
  </div>

  <div>
    <%= f.label :minutes %>
    <%= f.number_field :minutes %>
  </div>

  <div>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div>
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>

  <%= f.button %>
<% end %>

week4/timetracking/app/views/time_entries/edit.html.erb
<h2> Edit a time entry </h2>

<%= render "form" %>

week4/timetracking/app/views/time_entries/index.html.erb
<h2> List of time entries </h2>

<h3> <%= @my_project.name %> </h3>

<ul>
  <% @my_entries.each do |one_entry| %>
    <li>
      <%= one_entry.hours %> h
      <%= one_entry.minutes %> m -
      <%= one_entry.date %>

      <%= link_to "Edit", edit_project_time_entry_path(@my_project, one_entry) %>
      <%#= link_to "Edit", "/projects/#{@my_project.id}/time_entries/#{one_entry.id}/edit" %>

      <%= link_to "Delete", project_time_entry_path(@my_project, one_entry), method: "delete", data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new time entry", new_project_time_entry_path(@my_project) %>

week4/timetracking/app/views/time_entries/new.html.erb
<h2> Add a new time entry </h2>

<%= render "form" %>